/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PostPropertyRouteImport } from './routes/post-property'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InquiriesRouteImport } from './routes/inquiries'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as PropertiesIdIndexRouteImport } from './routes/properties.$id.index'
import { Route as PropertiesIdEditRouteImport } from './routes/properties.$id.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PostPropertyRoute = PostPropertyRouteImport.update({
  id: '/post-property',
  path: '/post-property',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiriesRoute = InquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdIndexRoute = PropertiesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PropertiesIdRoute,
} as any)
const PropertiesIdEditRoute = PropertiesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PropertiesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/inquiries': typeof InquiriesRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/post-property': typeof PostPropertyRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/properties/$id': typeof PropertiesIdRouteWithChildren
  '/properties/': typeof PropertiesIndexRoute
  '/properties/$id/edit': typeof PropertiesIdEditRoute
  '/properties/$id/': typeof PropertiesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/inquiries': typeof InquiriesRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/post-property': typeof PostPropertyRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/properties': typeof PropertiesIndexRoute
  '/properties/$id/edit': typeof PropertiesIdEditRoute
  '/properties/$id': typeof PropertiesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/inquiries': typeof InquiriesRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/post-property': typeof PostPropertyRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/properties/$id': typeof PropertiesIdRouteWithChildren
  '/properties/': typeof PropertiesIndexRoute
  '/properties/$id/edit': typeof PropertiesIdEditRoute
  '/properties/$id/': typeof PropertiesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/favorites'
    | '/inquiries'
    | '/login'
    | '/messages'
    | '/post-property'
    | '/profile'
    | '/signup'
    | '/properties/$id'
    | '/properties/'
    | '/properties/$id/edit'
    | '/properties/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/favorites'
    | '/inquiries'
    | '/login'
    | '/messages'
    | '/post-property'
    | '/profile'
    | '/signup'
    | '/properties'
    | '/properties/$id/edit'
    | '/properties/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/favorites'
    | '/inquiries'
    | '/login'
    | '/messages'
    | '/post-property'
    | '/profile'
    | '/signup'
    | '/properties/$id'
    | '/properties/'
    | '/properties/$id/edit'
    | '/properties/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FavoritesRoute: typeof FavoritesRoute
  InquiriesRoute: typeof InquiriesRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  PostPropertyRoute: typeof PostPropertyRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  PropertiesIdRoute: typeof PropertiesIdRouteWithChildren
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-property': {
      id: '/post-property'
      path: '/post-property'
      fullPath: '/post-property'
      preLoaderRoute: typeof PostPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiries': {
      id: '/inquiries'
      path: '/inquiries'
      fullPath: '/inquiries'
      preLoaderRoute: typeof InquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id/': {
      id: '/properties/$id/'
      path: '/'
      fullPath: '/properties/$id/'
      preLoaderRoute: typeof PropertiesIdIndexRouteImport
      parentRoute: typeof PropertiesIdRoute
    }
    '/properties/$id/edit': {
      id: '/properties/$id/edit'
      path: '/edit'
      fullPath: '/properties/$id/edit'
      preLoaderRoute: typeof PropertiesIdEditRouteImport
      parentRoute: typeof PropertiesIdRoute
    }
  }
}

interface PropertiesIdRouteChildren {
  PropertiesIdEditRoute: typeof PropertiesIdEditRoute
  PropertiesIdIndexRoute: typeof PropertiesIdIndexRoute
}

const PropertiesIdRouteChildren: PropertiesIdRouteChildren = {
  PropertiesIdEditRoute: PropertiesIdEditRoute,
  PropertiesIdIndexRoute: PropertiesIdIndexRoute,
}

const PropertiesIdRouteWithChildren = PropertiesIdRoute._addFileChildren(
  PropertiesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FavoritesRoute: FavoritesRoute,
  InquiriesRoute: InquiriesRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  PostPropertyRoute: PostPropertyRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  PropertiesIdRoute: PropertiesIdRouteWithChildren,
  PropertiesIndexRoute: PropertiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
